src/app/urls.py
from django.contrib import admin
from django.urls import path, include

from .view import home

urlpatterns = [
    path('', home, name='home'),
    path('admin/', admin.site.urls),
    path('post/', include('post.urls', 'post')),
]

src/post/urls.py
from django.urls import path
from .views import *

app_name = 'post'


urlpatterns = [
    path('', index, name='index'),
    path('create', create, name='create'),
    path('update/<slug>', update, name='update'),
    path('delete/<slug>', delete, name='delete'),
]

src/account/models.py
from django.db import models

# Create your models here.

src/post/models.py
import secrets

from django.db import models
from django.db.models.signals import pre_save
from django.dispatch import receiver
from django.utils.text import slugify
from django.utils import timezone


# Create your models here.
class PostModel(models.Model):
    title = models.CharField(max_length=50)
    content = models.TextField()
    author = models.CharField()
    created_at = models.DateTimeField(default=timezone.now)
    updated_at = models.DateTimeField(auto_now=True)
    slug = models.SlugField(max_length=16, blank=True, unique=True)


# Create slug
@receiver(pre_save, sender=PostModel)
def create_slug(sender, instance, **kwargs):
    if not instance.slug:
        base_slug = slugify(instance.title)[:8]
        random_part = secrets.token_urlsafe(8)[:8]
        new_slug = f"{base_slug}-{random_part}"

        while PostModel.objects.filter(slug=new_slug).exists():
            random_part = secrets.token_urlsafe(8)[:8]
            new_slug = f"{base_slug}-{random_part}"

        instance.slug = new_slug


pre_save.connect(create_slug, sender=PostModel)

src/account/views.py
from django.shortcuts import render

# Create your views here.

src/post/views.py
from operator import attrgetter

from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.db.models import Q
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect

from .form import CreatePostForm
from .models import PostModel


# index retrieve all data of search data.
def index(request):
    POSTS_PER_PAGE = 5
    context = {}
    # 'query' for search parameters | default is ""
    query = ""
    if request.GET:
        query = request.GET.get('q', '')
        context['query'] = str(query)

    # Query data follow by 'query' variable
    posts = sorted(get_blog_queries(query), key=attrgetter('updated_at'), reverse=True)

    # Paginate declare
    page = request.GET.get('page', POSTS_PER_PAGE)
    # Assign Paginator class with (list data & data per page)
    blog_posts_paginator = Paginator(posts, POSTS_PER_PAGE)

    # Set posts value for each paginated page
    try:
        posts = blog_posts_paginator.page(page)
    except PageNotAnInteger:
        posts = blog_posts_paginator.page(POSTS_PER_PAGE)
    except EmptyPage:
        posts = blog_posts_paginator.page(blog_posts_paginator.num_pages)

    # Assign posts to context dict
    context['posts'] = posts
    # return template and context data
    return render(request, 'index.html', context)


def create(request):
    context = {}
    # Get form field data
    form = CreatePostForm(request.POST or None)
    # Validate form
    if form.is_valid():
        # Save to database
        form.save()
    context['form'] = form
    # return template and context data
    return render(request, 'create.html', context)


def update(request, slug):
    context = {}
    # Get data or fail 404
    obj = get_object_or_404(PostModel, slug=slug)
    # Get form field data
    form = CreatePostForm(request.POST or None, instance=obj)
    # Validate form
    if form.is_valid():
        form.save()
        return redirect('post:index')
    context["form"] = form
    context["slug"] = slug
    # return template and context data
    return render(request, 'update.html', context)


def delete(request, slug):
    obj = get_object_or_404(PostModel, slug=slug)
    if request.method == 'POST':
        obj.delete()
        return redirect('post:index')


# Get data function affect by query
def get_blog_queries(query=None):
    # Create queries list
    queries = []
    # Split spaces foreach condition
    query = query.split(" ")
    # Loop through query
    for q in query:
        # posts is group posts data match query
        posts = PostModel.objects.filter(
            Q(title__icontains=q) |
            Q(content__icontains=q) |
            Q(author__icontains=q)
        ).distinct()
        # append all matching posts to queries
        for post in posts:
            if post not in queries:
                queries.append(post)
    # return a list of set would remove duplicates post
    return list(set(queries))

src/post/templates/create.html
{% extends "layouts/_base.html" %}

{% block content %}
    <div class="w-full h-full element-center">
        <form method="POST" id="" class="card-simple w-[720px]">
            {% csrf_token %}
            <div class="card-header">
                <h1 class="card-title text-slate-800 text-center">Add post</h1>
            </div>
            <div class="card-content">
                <div class="form-group">
                    <label for="title" class="input-label">Title</label>
                    <input type="text" id="title" class="form-input mx-auto" name="title" placeholder="Title">
                </div>
                <div class="form-group">
                    <label for="content" class="input-label">Content</label>
                    <input type="text" id="content" class="form-input mx-auto" name="content" placeholder="Content">
                </div>
                <div class="form-group">
                    <label for="author" class="input-label">Author</label>
                    <input type="text" id="author" class="form-input mx-auto" name="author" placeholder="Author">
                </div>
                <div class="mx-auto text-center mt-4">
                    <button type="submit"
                        class="bg-green-600 hover:bg-emerald-600 text-white font-medium px-8 py-2 rounded-lg">
                    Submit
                </button>
                </div>
            </div>
        </form>
    </div>
{% endblock content %}

src/post/templates/elements/paginate.html
<div class="flex justify-center">
    <ul class="pg-group">

        {% if post_paginate.has_previous %}
            <li>
                <a href="?{% if query %}q={{ query }}&{% endif %}page={{ post_paginate.previous_page_number }}"
                   class="pg-prev">
                    <span class="sr-only">Previous</span>
                    <svg class="w-2.5 h-2.5 rtl:rotate-180" aria-hidden="true" xmlns="http://www.w3.org/2000/svg"
                         fill="none" viewBox="0 0 6 10">
                        <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                              d="M5 1 1 5l4 4"></path>
                    </svg>
                </a>
            </li>
        {% endif %}

        {% for i in post_paginate.paginator.page_range %}
            {% if post_paginate.number == i %}
                <li><a class="pg-number-active">{{ i }}</a></li>
            {% else %}
                <li><a class="pg-number" href="?{% if query %}q={{ query }}&{% endif %}page={{ i }}">{{ i }}</a>
                </li>
            {% endif %}
        {% endfor %}

        {% if post_paginate.has_next %}
            <li>
                <a class="pg-next" href="?{% if query %}q={{ query }}&{% endif %}page={{ post_paginate.next_page_number }}">
                    <span class="sr-only">Next</span>
                    <svg class="w-2.5 h-2.5 rtl:rotate-180" aria-hidden="true" xmlns="http://www.w3.org/2000/svg"
                         fill="none" viewBox="0 0 6 10">
                        <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                              d="m1 9 4-4-4-4"></path>
                    </svg>
                </a>
            </li>
        {% endif %}
    </ul>
</div>

src/post/templates/elements/single_post.html
<div class="card-simple rounded-lg mt-8 w-[400px]">
    <div class="card-header">
        <h3 class="card-title">{{ post.title }}</h3>
    </div>
    <div class="card-content">
        <div class="my-4 mx-6">
            <p class="text-xl text-center text-slate-900 font-medium">{{ post.content }}</p>
            <p class="text-base text-end text-slate-700 font-thin">{{ post.author }}</p>
        </div>
    </div>
    <a href="{% url 'post:update' slug=post.slug %}" class="button-simple">Update Post</a>
</div>

src/post/templates/index.html
{% extends "layouts/_base.html" %}

{% block content %}
    <h1>Test</h1>
    <a href="{% url 'post:create' %}" class="button-simple">Create Post</a>
    <form method="GET" class="flex w-auto">
        <input type="text" name="q" class="form-input" placeholder="Title, author...">
        <button type="submit" class="button-simple">Search</button>
    </form>
    {% if posts %}
        {% for post in posts %}
            {% include 'elements/single_post.html' with post=post %}
        {% endfor %}
    {% else %}
        <div class="text-slate-700 text-xl">Not have any post</div>
    {% endif %}
    {% include 'elements/paginate.html' with post_paginate=posts %}

{% endblock content %}

src/post/templates/update.html
{% extends "layouts/_base.html" %}

{% block content %}
    <div class="w-full h-full element-center">
        <div class="card-simple w-[720px]">
            <form method="POST" id="" class="">
                {% csrf_token %}
                <div class="card-header">
                    <h1 class="card-title text-slate-800 text-center">Update post</h1>
                </div>
                <div class="card-content">
                    <div class="form-group">
                        <label for="title" class="input-label">Title</label>
                        <input type="text" id="title" class="form-input mx-auto" name="title" placeholder="Title"
                               value="{{ form.initial.title }}">
                    </div>
                    <div class="form-group">
                        <label for="content" class="input-label">Content</label>
                        <input type="text" id="content" class="form-input mx-auto" name="content" placeholder="Content"
                               value="{{ form.initial.content }}">
                    </div>
                    <div class="form-group">
                        <label for="author" class="input-label">Author</label>
                        <input type="text" id="author" class="form-input mx-auto" name="author" placeholder="Author"
                               value="{{ form.initial.author }}">
                    </div>
                </div>
                <div class="mx-auto text-center mt-4">
                    <button type="submit"
                            class="bg-green-600 hover:bg-emerald-600 text-white font-medium px-8 py-2 rounded-lg">
                        Submit
                    </button>
                    <button id="handle-delete" class="button-gradient">Delete</button>
                </div>
            </form>
        </div>

        <form id="form-deleting" method="POST" class="hidden" action="{% url 'post:delete' slug=slug %}">
            {% csrf_token %}
        </form>
    </div>
    <script type="text/javascript">
        const btnHandleDelete = document.getElementById("handle-delete")
        const funcDeleting = document.getElementById("form-deleting")

        btnHandleDelete.onclick = (e) => {
            e.preventDefault()
            funcDeleting.submit()
        }
    </script>
{% endblock content %}

src/templates/homepage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>This is the homepage</h1>
</body>
</html>

src/templates/layouts/_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Django + Tailwind CSS + Flowbite</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/output.css' %}">
</head>
<body class="bg-green-50">
    {% include 'layouts/navbar.html' %}
    <div class="container mx-auto mt-4">
        {% block content %}
        {% endblock content %}
    </div>

</body>
</html>

src/templates/layouts/navbar.html
{% load static %}
    <nav class="nav">
        <div class="navbar">
            <a href="" class="flex">
                <img src="{% static 'assets/python-icon.png' %}" class="h-8 w-8" alt="Flowbite Logo"/>
                <span class="self-center text-2xl font-semibold whitespace-nowrap dark:text-white"></span>
            </a>

            <button data-collapse-toggle="navbar-dropdown" type="button"
                    class="inline-flex items-center p-2 w-10 h-10 justify-center text-sm text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600"
                    aria-controls="navbar-dropdown" aria-expanded="false">
                <span class="sr-only">Open main menu</span>
                <svg class="w-5 h-5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none"
                     viewBox="0 0 17 14">
                    <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                          d="M1 1h15M1 7h15M1 13h15"></path>
                </svg>
            </button>

            <div class="hidden w-full md:block md:w-auto" id="navbar-dropdown">
                <ul class="flex flex-col font-medium p-4 md:p-0 mt-4 border border-gray-100 rounded-lg bg-gray-50 md:space-x-8 rtl:space-x-reverse md:flex-row md:mt-0 md:border-0 md:bg-white dark:bg-gray-800 md:dark:bg-gray-900 dark:border-gray-700">
                    <li>
                        <a href=""
                           class="block items-center py-2 px-3 text-white bg-blue-700 rounded md:bg-transparent md:text-blue-700 md:p-0 md:dark:text-blue-500 dark:bg-blue-600 md:dark:bg-transparent"
                           aria-current="page">Trang chủ</a>
                    </li>
                    <li>
                        <a href=""
                           class="nav-item">Chọn số
                        </a>
                    </li>
                    <li>
                        <a href=""
                           class="nav-item">Thông
                            tin</a>
                    </li>
                        <li>
                            <button id="dropdownAdmNavbarLink" data-dropdown-toggle="dropdownAdmNavbar"
                                    class="flex items-center justify-between w-full py-2 px-3 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 md:w-auto dark:text-white md:dark:hover:text-blue-500 dark:focus:text-white dark:border-gray-700 dark:hover:bg-gray-700 md:dark:hover:bg-transparent">
                                Quản trị
                                <svg class="w-2.5 h-2.5 ms-2.5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg"
                                     fill="none" viewBox="0 0 10 6">
                                    <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"
                                          stroke-width="2"
                                          d="m1 1 4 4 4-4"></path>
                                </svg>
                            </button>
                            <!-- Dropdown menu -->
                            <div id="dropdownAdmNavbar"
                                 class="nav-item-dropdown">
                                <ul class="py-2 text-sm text-gray-700 dark:text-gray-400"
                                    aria-labelledby="dropdownLargeButton">
                                    <li>
                                        <a href=""
                                           class="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">Quản
                                            lý tài khoản</a>
                                    </li>
                                    <li>
                                        <a href=""
                                           class="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">Thêm
                                            tài khoản</a>
                                    </li>
                                </ul>
                                <ul class="block py-2 text-sm text-gray-700">
                                    <li>
                                        <a href=""
                                           class="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">Quản
                                            lý sự kiện</a>
                                    </li>
                                    <li>
                                        <a href=""
                                           class="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">Thêm
                                            sự kiện</a>
                                    </li>
                                </ul>
                            </div>
                        </li>
{#                        <li>#}
{#                            <button id="dropdownNavbarLink" data-dropdown-toggle="dropdownNavbar"#}
{#                                    class="flex items-center justify-between w-full py-2 px-3 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 md:w-auto dark:text-white md:dark:hover:text-blue-500 dark:focus:text-white dark:border-gray-700 dark:hover:bg-gray-700 md:dark:hover:bg-transparent">#}
{#                                Xin chào, #}
{#                                <svg class="w-2.5 h-2.5 ms-2.5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg"#}
{#                                     fill="none" viewBox="0 0 10 6">#}
{#                                    <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"#}
{#                                          stroke-width="2"#}
{#                                          d="m1 1 4 4 4-4"></path>#}
{#                                </svg>#}
{#                            </button>#}
{#                            <!-- Dropdown menu -->#}
{#                            <div id="dropdownNavbar"#}
{#                                 class="z-10 hidden font-normal bg-white divide-y divide-gray-100 rounded-lg shadow w-44 dark:bg-gray-700 dark:divide-gray-600">#}
{#                                <ul class="py-2 text-sm text-gray-700 dark:text-gray-400"#}
{#                                    aria-labelledby="dropdownLargeButton">#}
{#                                    <li>#}
{#                                        <a href=""#}
{#                                           class="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">Thông#}
{#                                            tin tài khoản</a>#}
{#                                    </li>#}
{#                                    <li>#}
{#                                        <a href=""#}
{#                                           class="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">Đổi#}
{#                                            mật khẩu</a>#}
{#                                    </li>#}
{#                                </ul>#}
{#                                <div class="py-1">#}
{#                                    <a href=""#}
{#                                       class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white">Đăng xuất</a>#}
{#                                </div>#}
{#                            </div>#}
{#                        </li>#}
                        <li>
                            <a href=""
                               class="nav-item">Đăng
                                nhập</a>
                        </li>
                </ul>
            </div>
        </div>
    </nav>